#!/bin/bash

# Display a dialog to select a browser
browser=$(yad --title="Select Browser" \
              --image="web-browser" \
              --text="Choose a browser" \
              --button="Firefox ":2 \
              --button="Brave":3 \
              --button="Thorium":4 \
              --button="(x)":1 \
              --width=350 \
              --height=120 \
              --center)

case $? in
    2)
        /usr/bin/firefox-developer-edition "$1" &
        ;;
    3)
        /usr/bin/brave "$1" &
        ;;
    4)
        /usr/bin/thorium-browser "$1" &
        ;;
    *)
        # User canceled the dialog
        echo "Operation canceled."
        ;;
esac

exit 0


