#!/bin/bash

# Show chooser
browser=$(yad --title="Select Browser" \
              --image="web-browser" \
              --text="Choose a browser" \
              --button="Brave":2 \
              --button="Firefox":3 \
              --button="Chromium":4 \
              --button="(x)":1 \
              --width=350 \
              --height=120 \
              --center)

case $? in
    2)
        if [[ -n "$1" ]]; then
            /usr/bin/brave-beta --password-store=basic "$1" &
        else
            /usr/bin/brave-beta --password-store=basic &
        fi
        ;;
    3)
        if [[ -n "$1" ]]; then
            /usr/bin/firefox-developer-edition "$1" &
        else
            /usr/bin/firefox-developer-edition &
        fi
        ;;
    4)
        if [[ -n "$1" ]]; then
            /usr/bin/chromium "$1" &
        else
            /usr/bin/chromium &
        fi
        ;;
    *)
        echo "Operation canceled."
        ;;
esac

exit 0
