#!/bin/bash

# Display a dialog to select a browser
browser=$(yad --title="Select Browser" \
              --image="web-browser" \
              --text="Choose a browser" \
              --button="Personal":2 \
              --button="Work":3 \
              --button="Extra":4 \
              --button="(x)":1 \
              --width=350 \
              --height=120 \
              --center)

case $? in
    2)
        /usr/bin/brave-beta --password-store=basic "$1" &
        ;;
    3)
        /usr/bin/brave --password-store=basic "$1" &
        ;;
    4)
        /usr/bin/chromium "$1" &
        ;;
    *)
        # User canceled the dialog
        echo "Operation canceled."
        ;;
esac

exit 0


