#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#47e2f240'
TEXT='#fafafaFF'
WRONG='#d9021b'
VERIFYING='#10c76b'

/usr/bin/i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$VERIFYING     \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--time-str="%I:%M %p"        \
--date-str="%A, %b %d"       \
-i ~/Pictures/tech2.jpg
