#!/bin/bash

# Path to wallpaper (change this if you want a different one)
#WALLPAPER="$HOME/Pictures/space14.jpg"
#
## Update lock screen background (only needed once unless wallpaper changes)
#betterlockscreen -u "$WALLPAPER"

# Pause notifications (dunst)
pkill -u "$USER" -USR1 dunst

# Lock the screen with blur
betterlockscreen -l dimblur --time-format "%I:%M %p"

# Resume notifications after unlock
pkill -u "$USER" -USR2 dunst
