#!/usr/bin/env bash

ignore_list=(
    "node_modules"
    ".git"
    ".github"
    ".gitignore"
    ".gitmodules"
    ".gitattributes"
    ".gitlab-ci.yml"
    ".gitkeep"
    ".gitlab"
    ".gitlab-ci"
    ".gitlab-ci.yml"
    "build"
    "dist"
    "target"
    "out"
    "obj"
)

find_cmd="find ~/dev ~/lync ~/learning ~/dotfiles ~/.config -maxdepth 4 -mindepth 1 -type d "

for folder in "${ignore_list[@]}"; do
    find_cmd+=" -name \"$folder\" -prune -o "
done

find_cmd+=" -print -type d"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(eval $find_cmd | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
