# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' 
error_symbol = '[x](bold red)' 

[aws]
symbol = "  "
format = '[${symbol}(${version} )]($style)'

[buf]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[c]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[conda]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[dart]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[directory]
read_only = " 󰌾"
truncate_to_repo = true
truncation_length = 8
truncation_symbol = ".| "

[docker_context]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[elixir]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[elm]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[golang]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[guix_shell]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[haskell]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[haxe]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[julia]
symbol = " "

[lua]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "
format = '[${symbol}(${version} )]($style)'

[nim]
symbol = "󰆥 "
format = '[${symbol}(${version} )]($style)'

[nix_shell]
symbol = " "
format = ' [${symbol}(${version} )]($style)'

[nodejs]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = true

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[rust]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[scala]
symbol = " "
format = '[${symbol}(${version} )]($style)'

# disable the battery module
[battery]
disabled = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$character"""

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = '. [$duration](bold yellow)'
