[colors]
background = #222
background-alt = #444
foreground = #dfdfdf
foreground-alt = #888
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/mypolybar]
monitor = DP-0
dpi = 192
width = 100%
height = 2.5%
radius = 6.0
fixed-center = false
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

border-top-size = 3
border-top-color = #303846

border-bottom-size = 0
border-left-size = 0
border-right-size = 0

line-size = 2

padding = 1
module-margin = 1

font-0 = "Noto Sans Mono:size=11;1"
font-1 = "Noto Sans Mono:size=11;1"
font-2 = "Noto Sans Symbols:size=11;1"
font-3 = "Noto Sans Symbols2:size=11;1"
font-4 = "Font Awesome 7 Free Solid:style=Solid:size=11;2"
font-5 = "Font Awesome 7 Free:style=Regular:size=11"
font-6 = "Font Awesome 7 Brands:style=Regular:size=11"
font-7 = "Fira Code Nerd Font:size=12"
font-8 = "Fira Code Nerd Font:size=15"

modules-left = public-ip xworkspaces ffmpeg-rec
modules-center =
modules-right = pulseaudio mouse-battery network-speed cpu gpu filesystem memory date time lock

# for discord, etc
#tray-position = right
#tray-padding = 2
#tray-maxsize = 24

wm-restack = i3
# don't hide the bar when going fullscreen

[bar/mypolybar1]
monitor = HDMI-1
dpi = 165
width = 100%
height = 2.5%
radius = 6.0
fixed-center = false
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 0
line-size = 2
padding = 1
module-margin = 1

font-0 = "Noto Sans Mono:size=11;1"
font-1 = "Noto Sans Mono:size=11;1"
font-2 = "Noto Sans Symbols:size=11;1"
font-3 = "Noto Sans Symbols2:size=11;1"
font-4 = "Font Awesome 7 Free Solid:style=Solid:size=11;2"
font-5 = "Font Awesome 7 Free:style=Regular:size=11"
font-6 = "Font Awesome 7 Brands:style=Regular:size=11"
font-7 = "Fira Code Nerd Font:size=12"
font-8 = "Fira Code Nerd Font:size=15"

modules-left = xwindow
modules-center =
modules-right = time-seconds date-full

# for discord, etc
#tray-position = right
#tray-padding = 2
#tray-maxsize = 24

wm-restack = i3
# don't hide the bar when going fullscreen


[bar/mypolybar2]
monitor = HDMI-1
dpi = 165
width = 100%
height = 2.2%
radius = 6.0
fixed-center = false
bottom = false

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 0
line-size = 2
padding = 1
module-margin = 1

font-0 = "Noto Sans Mono:size=11;1"
font-1 = "Noto Sans Mono:size=11;1"
font-2 = "Noto Sans Symbols:size=11;1"
font-3 = "Noto Sans Symbols2:size=11;1"
font-4 = "Font Awesome 7 Free Solid:style=Solid:size=11;2"
font-5 = "Font Awesome 7 Free:style=Regular:size=11"
font-6 = "Font Awesome 7 Brands:style=Regular:size=11"
font-7 = "Fira Code Nerd Font:size=12"
font-8 = "Fira Code Nerd Font:size=15"

modules-left = spotify
modules-center =
modules-right = updates-arch pulseaudio dunst powermenu

# for discord, etc
#tray-position = right
#tray-padding = 2
#tray-maxsize = 24

wm-restack = i3

[module/mouse-battery]
type = custom/script
exec = ~/.config/polybar/scripts/mouse-battery.sh
interval = 150
click-left = /usr/bin/openlogi-desktop


[module/cpu-temp]
type = custom/script
exec = ~/.config/polybar/scripts/cpu_temp.sh
interval = 3
format = <label>
format-prefix = " "
format-underline = #FF8A8A
label = %output%


[global/wm]
margin-top = 0

[module/ffmpeg-rec]
type = custom/script
exec = ~/.config/polybar/scripts/ffmpeg_rec_status.sh
interval = 2
format = <label>
label = %output%
click-left = ~/.config/scripts/record_region.sh


[module/lily58_battery]
type = custom/script
interval = 300
exec = ~/.config/polybar/scripts/lily58_battery.sh
format = <label>


[module/xwindow]
type = internal/xwindow
label = %title:0:68:...%


[module/updates-arch]
type = custom/script
exec = "~/.config/polybar/scripts/arch_updates.sh"
tail = true
format = <label>
format-prefix =
interval = 3600



[module/powermenu]
type = custom/script
label = ""
exec = ~/.config/polybar/scripts/popup-powermenu.sh
;interval = 5
click-left = ~/.config/polybar/scripts/popup-powermenu.sh --popup &
format-foreground = ${colors.alert}


[module/lock]
type = custom/text
label = ""
format-prefix = ""
format-underline = ${colors.alert}
click-left = ~/.config/scripts/lock

[module/xworkspaces]
type = internal/xworkspaces

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5 
icon-5 = 6;6 󰓇
icon-6 = 7;7 󰭻
icon-7 = 8;8 
icon-8 = 9;
icon-9 = 10;'


label-active = %icon%
label-active-underline= #FF9933
label-active-overline= #4FC3F7
label-active-padding = 1

label-occupied = %icon%
label-occupied-padding = 1
label-occupied-foreground = ${colors.foreground-alt}

label-urgent = %icon%.
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

; reverse-scroll = true
enable-scroll = false



[module/filesystem]
type = internal/fs

mount-0 = /
interval = 30
fixed-values = true
spacing = 4
warn-percentage = 75
format-mounted = <label-mounted>
format-unmounted = <label-unmounted>
format-mounted-underline = #0a6cf5
format-mounted-prefix = " "

label-mounted = %free%
label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = #55


[module/eth1]
type = internal/network
interface = enp42s0
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = "🖧 "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =


[module/cpu]
type = custom/script
exec = ~/.config/polybar/scripts/cpu_usage_temp.sh
interval = 5

format = <label>
format-prefix = "CPU:"
format-underline = #FF8A8A
label = %output%


[module/gpu]
type = custom/script
exec = ~/.config/polybar/scripts/gpu.sh
interval = 3
format = <label>
format-prefix = ""
format-underline = #FF6EC7
label = %output%


[module/memory]
type = internal/memory
interval = 2

format-prefix = " "
format-underline = #D37506

label = %gb_used:0:3%/%gb_total:0:4% GB



[module/wlan]
type = internal/network
interface = wlan0
interval = 5.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

label-disconnected =

ramp-signal-0 = 🌧
ramp-signal-1 = 🌦
ramp-signal-2 = 🌥
ramp-signal-3 = 🌤
ramp-signal-4 = 🌣

[module/date-full]
type = internal/date
interval = 30

date = "%d/%b/%Y %a"

format-prefix = " "
format-underline = #01949A
label = %date%

[module/date]
type = internal/date
interval = 30

date = "%d.%b.'%y %a"

format-prefix = " "
format-underline = #01949A
label = %date%

[module/time-seconds]
type = internal/date
interval = 1
time = %I:%M:%S %p

format-prefix = " "
format-underline = #8a53a6
label = %time%

[module/time]
type = internal/date
interval = 30
time = %I:%M %p

format-prefix = " "
format-underline = #8a53a6
label = %time%

[module/pulseaudio]
type = custom/script

exec = ~/.config/polybar/scripts/audio_status.sh
tail = true

format = <label>
label = %output%

click-left = pactl set-sink-mute @DEFAULT_SINK@ toggle
click-middle = ~/.config/polybar/scripts/volume_slider.sh
click-right = pavucontrol

scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%

[module/spotify]
type = custom/script

exec = ~/.config/polybar/scripts/scroll_spotify_status.sh
tail = true

format = <label>
format-underline = #1DB954

click-left = playerctl play-pause -p spotify
click-middle = playerctl previous -p spotify
click-right = playerctl next -p spotify


[module/spotify-icon]
type = custom/text
label = "󰓇"
format-foreground = #1DB954


[module/spotify-back]
type = custom/text
label = ""
click-left = playerctl previous -p spotify

[module/spotify-playpause]
type = custom/script
interval = 1
tail = true
format = <label>
; prefix for the spotify logo
;format-prefix = "󰓇 "
; Run small inline command to get Play or Pause icon
exec = bash -c 'playerctl status -p spotify 2>/dev/null | grep -q Playing && echo "" || echo ""'
; Click actions
click-left = playerctl play-pause -p spotify

[module/spotify-playpause-colored]
type = custom/script
interval = 1
tail = true
format = <label>
format-underline = #1DB954
; prefix for the spotify logo
;format-prefix = "󰓇 "
; Run small inline command to get Play or Pause icon
exec = bash -c 'playerctl status -p spotify 2>/dev/null | grep -q Playing && echo "  " || echo "  "'
; Click actions
click-left = playerctl play-pause -p spotify
click-right = i3-msg workspace 7

[module/spotify-next]
type = custom/text
label = ""
click-left = playerctl next -p spotify


[module/dunst]
type = custom/script

exec = ~/.config/polybar/scripts/dunst.sh status
interval = 2

format = <label>
label = %output%
click-left = ~/.config/polybar/scripts/dunst.sh display-history 6
click-middle = ~/.config/polybar/scripts/dunst.sh toggle
click-right = ~/.config/polybar/scripts/dunst.sh clear

[module/bt-headset-battery]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth_headphone_battery.sh
interval = 30

format = <label>
format-underline = #4A90E2
label = %output%



[module/public-ip]
type = custom/script

exec = ~/.config/polybar/scripts/public_ip.sh
interval = 1

format = <label>
label = %output%

# Reveal cached IPv4
click-left = ~/.config/polybar/scripts/public_ip.sh --reveal-v4

# Force-refresh IPv4 + IPv6 cache
click-middle = ~/.config/polybar/scripts/public_ip.sh --refresh

# Reveal cached IPv6
click-right = ~/.config/polybar/scripts/public_ip.sh --reveal-v6

# Immediately hide any revealed IP
scroll-up = ~/.config/polybar/scripts/public_ip.sh --hide
scroll-down = ~/.config/polybar/scripts/public_ip.sh --hide

[module/network-speed]
type = internal/network

interface = enp42s0
interval = 1

format-connected = <label-connected>
format-connected-underline = #4CAF50
format-disconnected = <label-disconnected>

label-connected = "↓%downspeed% ↑%upspeed%"

[settings]
screenchange-reload = true
enable-ipc = true

; vim:ft=dosini
